export const AGREGAR_CLIENTES = 'AGREGAR_CLIENTES';
export const AGREGAR_CLIENTES_EXITO = 'AGREGAR_CLIENTES_EXITO';
export const AGREGAR_CLIENTES_ERROR = 'AGREGAR_CLIENTES_ERROR';

//descargar clientes
export const COMENZAR_DESCARGA_CLIENTES = 'COMENZAR_DESCARGA_CLIENTES';
export const DESCARGA_CLIENTES_EXITO = 'DESCARGA_CLIENTES_EXITO';
export const DESCARGA_CLIENTES_ERROR = 'DESCARGA_CLIENTES_ERROR';

//editar clientes
export const OBTENER_CLIENTE ='OBTENER_CLIENTE';
export const COMENZAR_EDICION_CLIENTE='COMENZAR_EDICION_CLIENTE';
export const EDITAR_CLIENTE_EXITO = 'EDITAR_CLIENTE_EXITO';
export const EDITAR_CLIENTE_ERROR = 'EDITAR_CLIENTE_ERROR';

//eliminar clientes
export const COMENZAR_ELIMINAR_CLIENTE = 'COMENZAR_ELIMINAR_CLIENTE';
export const ELIMINAR_CLIENTE_EXITO = 'ELIMINAR_CLIENTE_EXITO';
export const ELIMINAR_CLIENTE_ERROR = 'ELIMINAR_CLIENTE_ERROR';